import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Authorless</title>
        <meta name="This is an authorless platform, where individuals with simlar views can collaborate on various art forms to produce valuable user content." content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero/>
      </main>
     

    </div>
  )
}

export default Home
